---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-equal
  labels:
    app.kubernetes.io/version: "1.0.0"
spec:
  params:
    - name: left
      type: string
    - name: right
      type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      if [ "$(params.left)" = "$(params.right)" ]; then
        echo "$(params.left) == $(params.right)"
        exit 0
      else
        echo "$(params.left) != $(params.right)"
        exit 1
      fi
