---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory-cr-add
  labels:
    app.kubernetes.io/version: "2.0.0"
    tekton.dev/deprecated: true
spec:
  params:
    - name: change-request-id
      descripton: unique servicenow change request id
    - name: application
      description: application name to add to the change request
    - name: inventory-folder
      description: directory name where the inventory located
    - name: git-api-token-key
      description: github enterprise api token secret name
      default: "git-token"
    - name: target-environment
      description: deployment target environment
    - name: retry-count
      description: retry count to pull and push git evidence repo
      default: "5"
    - name: retry-delay
      description: the amount of seconds between the retries
      default: "5"
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"

  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']

  steps:
    - name: add-change-request
      image: ibmcom/pipeline-base-image:2.6@sha256:7f588468622a981f89cf5e1212aaf75fface9da6169b5345ca52ab63d8215907
      env:
        - name: CHANGE_REQUEST_ID
          value: $(params.change-request-id)
        - name: APPLICATION
          value: $(params.application)
        - name: INVENTORY_FOLDER
          value: $(params.inventory-folder)
      script: |
        #!/bin/bash
        set -e -o pipefail;

        if [ "$PIPELINE_DEBUG" == 1 ]; then
          env
          trap env EXIT
          set -x
        fi

        GIT_TOKEN=$(cat "/secrets/$(params.git-api-token-key)")

        git config --global user.email "tekton@example.com"
        git config --global user.name "Tekton"

        clone_inventory_script() {
          git clone "https://$GIT_TOKEN@github.ibm.com/cocoa/inventory-script.git"
          export PATH="$(pwd)/inventory-script:$PATH"
        }

        update_inventory_branch() {

          cd /artifacts/$INVENTORY_FOLDER

          inventory promote "$APPLICATION" "$(params.target-environment)"_candidate "$(params.target-environment)" "$CHANGE_REQUEST_ID"
        }

        source /scripts/retry_command.sh

        retry $(params.retry-count) $(params.retry-delay) clone_inventory_script

        exit_code=$?

        if [ $exit_code -ne 0 ]; then
          echo "Error cloning inventory script repositry. There might be a github downtime, you can check it here: https://ibmtoolbox.statuspage.io"
          exit $exit_code
        fi

        retry $(params.retry-count) $(params.retry-delay) update_inventory_branch

        exit_code=$?

        if [ $exit_code -ne 0 ]; then
          echo "Error adding the inventory update to the inventory branch. There might be a github downtime, you can check it here: https://ibmtoolbox.statuspage.io"
          exit $exit_code
        fi

      volumeMounts:
        - mountPath: /scripts
          name: retry-command

  workspaces:
    - name: artifacts
      mountPath: /artifacts
    - name: secrets
      mountPath: /secrets

  volumes:
    - name: retry-command
      configMap:
        name: retry-command
        items:
          - key: retry_command.sh
            path: retry_command.sh
