---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ciso-image-sign
  labels:
    tekton.dev/deprecated: true
    app.kubernetes.io/version: 2.0.0
spec:
  params:
    - name: registry-region
    - name: image
    - name: image-digest
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: secure-properties
    - name: toolchain-apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud kubernetes service
      default: "api-key"
    - name: vault-secret
      default: vault-secret
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: evidence
      default: 'signature-evidence.json'
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
    - name: break-glass-name
      description: Name of the `ConfigMap` that holds Break-Glass mode settings
      default: environment-properties
    - name: break-glass-key
      description: Key in the `break-glass-name` `ConfigMap` that holds the Break-Glass mode settings
      default: break_glass
  volumes:
    - name: secrets
      secret:
        secretName: $(params.continuous-delivery-context-secret)
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  results:
    - name: exit-code
      description: The exit-code of the script
    - name: status
      description: The status based on exit-code
    - name: signature
      description: Signature data file name
    - name: signature-content
      description: the signature data
  steps:
    - name: sign-image
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/csso-image-sign:1.0.0@sha256:cb22e6ad6b3469155719f6bf09bde641208a1e349e5ccc09407204bb069f7b4e
      env:
        - name: VAULT_SECRET
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.vault-secret)
        - name: BREAK_GLASS
          valueFrom:
            configMapKeyRef:
              name: $(params.break-glass-name)
              key: $(params.break-glass-key)
              optional: true
        - name: REGISTRY_REGION
          value: $(params.registry-region)
        - name: IMAGE
          value: $(params.image)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
        - name: API
          value: $(params.ibmcloud-api)
      volumeMounts:
        - mountPath: /secrets
          name: secrets
      script: |
          #!/bin/bash

          set +e

          if [[ -n "$BREAK_GLASS" ]]; then
            echo -n $(params.evidence) | tee $(results.signature.path)
            echo -n 0 | tee $(results.exit-code.path)
            echo -n skipped | tee $(results.status.path)
            echo "Break-Glass mode is on, skipping the rest of the task..."
            exit 0
          fi

          export IBM_CLOUD_API_KEY=$(cat "/secrets/$(params.toolchain-apikey-secret-key)")

          TARGET_REGION=$(echo "${REGISTRY_REGION}" | awk -F ":" '{print $NF}')
          ibmcloud login -a ${API} --apikey ${IBM_CLOUD_API_KEY} -r ${TARGET_REGION}

          #REGISTRY_URL - the registry URL e.g. us.icr.io, de.icr.io
          REGISTRY_URL=$(echo "$IMAGE" | cut -f1 -d/)

          network_access=$(curl https://w3.ibm.com)
          if [[ "${network_access}" ]]; then
            echo "CISO service reachable"
          else
            echo "No access to internal network. Check that the worker has access"
          fi

          KEY_NAME="temp.pfx"
          echo "RESTORING KEY DATA"
          echo -n "$VAULT_SECRET" | base64 -d > $KEY_NAME
          mv ./$KEY_NAME /etc/ekm
          echo "****************"

          #extract alias
          ALIAS=$(ucl list | grep -m 1 Private)
          if [[ "$ALIAS" ]]; then
            echo "Certificate found"
          else
            STR=$(ucl list)
            if grep -q "Error" <<< "$STR"; then
              echo "Cannot access CISO partition."
              echo "Ensure that CISO account has been setup and that the client key secret is correct"
            else
              echo "Ensure that your CISO partition has a signing certifcate provisioned"
            fi
          fi
          ALIAS=${ALIAS#*"UID="}
          ALIAS=$(echo $ALIAS | head -n1 | sed -e 's/\s.*$//')
          echo "Alias: $ALIAS"

          gpgconf --kill all
          ucl pgp-key -u ${ALIAS}
          FINGERPRINT=$(gpg2 -k)
          FINGERPRINT=${FINGERPRINT#*"[SCEA]"}
          FINGERPRINT=$(echo $FINGERPRINT | head -n1 | sed -e 's/\s.*$//')
          SIGNING_DIR="signing"
          mkdir ${SIGNING_DIR}

          SIGNING_KEY=${FINGERPRINT}

          if [[ "$SIGNING_KEY" ]]; then
              echo "SIGNING REPO"
              skopeo copy docker://${IMAGE} docker://${IMAGE} --dest-creds iamapikey:${IBM_CLOUD_API_KEY} --src-creds iamapikey:${IBM_CLOUD_API_KEY} --sign-by ${SIGNING_KEY}
          else
              echo "No key found. Unable to sign"
          fi
          PASS=$?
          echo $PASS | tee $(results.exit-code.path)
          if [[ "$SIGNING_KEY" && "$PASS" == 0 ]]; then
            echo "No issues were found"
            IAMBEARER=$(ibmcloud iam oauth-tokens | awk '/IAM/ { print $4; }')
            NAME=$(echo $IMAGE | cut -d: -f1 | cut -d/ -f2,3)
            TOKEN=$(curl -s \
            -F "service=registry" \
            -F "grant_type=password" \
            -F "client_id=curlsig" \
            -F "username=iambearer" \
            -F "password=${IAMBEARER}" \
            -F "scope=repository:${NAME}:pull" \
            https://${REGISTRY_URL}/oauth/token | jq -r .token)

            SIGNATURES=$(curl -s -H "Authorization: Bearer ${TOKEN}" https://${REGISTRY_URL}/extensions/v2/${NAME}/signatures/${IMAGE_DIGEST} | jq '.signatures')

            COUNT=$(echo "${SIGNATURES}" | jq '. | length')
            INDEX=$(echo "$((COUNT - 1))")
            echo "SIGNATURE INDEX ${INDEX}"

            SIGNATURE_DATA=$(echo "$SIGNATURES" | jq --arg jq_index "$INDEX" '.[$jq_index|tonumber]')
            echo -n success | tee $(results.status.path)

            #create evidence json
            cd /artifacts
            echo ${SIGNATURE_DATA} > $(params.evidence)
            SIGNATURE_CONTENT=$(echo "${SIGNATURE_DATA}" | jq -r '.content')
            echo -n $(params.evidence) | tee $(results.signature.path)
            echo -n "${SIGNATURE_CONTENT}" | tee $(results.signature-content.path)
          else
            echo "Signing failed."
            cd /artifacts
            echo -n failure | tee $(results.status.path)
            echo {} > $(params.evidence)
            echo -n $(params.evidence) | tee $(results.signature.path)
          fi

  workspaces:
    - name: artifacts
      description: A workspace backing by a volume
      mountPath: /artifacts
